<a href="https://colab.research.google.com/github/blackwithwhitegreen/Pytorch/blob/main/Mathematical_operation_in_Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [4]:
x = torch.rand(2,2)
x

tensor([[0.7264, 0.9313],
        [0.7546, 0.8202]])

In [3]:
# Addition
x +2

tensor([[2.9212, 2.2503],
        [2.5438, 2.6459]])

In [5]:
# Substract
x - 2

tensor([[-1.2736, -1.0687],
        [-1.2454, -1.1798]])

In [6]:
# Multiplication
x * 2

tensor([[1.4527, 1.8626],
        [1.5091, 1.6405]])

In [7]:
# Division
x / 2

tensor([[0.3632, 0.4656],
        [0.3773, 0.4101]])

In [8]:
# integer division
(x*100)//2

tensor([[36., 46.],
        [37., 41.]])

In [9]:
# mod
((x*100)//2)%2

tensor([[0., 0.],
        [1., 1.]])

In [10]:
# power
x**2

tensor([[0.5276, 0.8673],
        [0.5693, 0.6728]])

#Tensor more then one.

In [12]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.7521, 0.5387, 0.6369],
        [0.3089, 0.0629, 0.9431]])
tensor([[0.5042, 0.8991, 0.7346],
        [0.9120, 0.3331, 0.0346]])


In [13]:
# add
a + b

tensor([[1.2564, 1.4378, 1.3716],
        [1.2209, 0.3960, 0.9777]])

In [14]:
# substract
a - b

tensor([[ 0.2479, -0.3604, -0.0977],
        [-0.6031, -0.2702,  0.9084]])

In [15]:
# multiplication
a * b

tensor([[0.3792, 0.4843, 0.4679],
        [0.2817, 0.0209, 0.0327]])

In [16]:
# division
a / b

tensor([[ 1.4917,  0.5992,  0.8670],
        [ 0.3387,  0.1888, 27.2241]])

In [17]:
# power
a ** b

tensor([[0.8662, 0.5734, 0.7179],
        [0.3425, 0.3979, 0.9980]])

In [23]:
# mod
a*1000000
b*100

a%b

tensor([[0.2479, 0.5387, 0.6369],
        [0.3089, 0.0629, 0.0078]])

In [24]:
c = torch.tensor([1,-2,3,-4])

In [25]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [26]:
# negitive
torch.neg(c)

tensor([-1,  2, -3,  4])

In [27]:
d = torch.tensor([1.3,3.4,4.4,5.9])

In [30]:
# round
torch.round(d)

tensor([1., 3., 4., 6.])

In [31]:
# ceil
torch.ceil(d)

tensor([2., 4., 5., 6.])

In [33]:
# floor
torch.floor(d)

tensor([1., 3., 4., 5.])

In [34]:
#clamp
torch.clamp(d,min=2,max=3)

tensor([2., 3., 3., 3.])