<a href="https://colab.research.google.com/github/blackwithwhitegreen/Pytorch/blob/main/Tensor_creating_and_data_type.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

In [3]:
print(torch.__version__)

2.5.1+cu124


#Creating Tensor.

#Empty function allocate the memory, it does not assign the values its just show the values present on that particular location.

In [7]:
torch.empty(2,3)

tensor([[1.2613e-37, 4.3199e-41, 1.2613e-37],
        [4.3199e-41, 4.4842e-44, 0.0000e+00]])

#Torch.Zeros used to  initilizes the zeroes.

In [9]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

#Torch.ones used to initilizes the Ones.

In [10]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
torch.rand(2,3)

tensor([[0.7874, 0.7841, 0.8601],
        [0.1703, 0.5433, 0.3097]])

#Seed is similiar to the rand but it gives the same values of matrix if other one is using the seed.

#Basically it fullfill the reproducibility isseue.

In [14]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

#for Creating custom Tensors

In [16]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [17]:
# Arange

print("Using arange ->",torch.arange(0,10,2))

Using arange -> tensor([0, 2, 4, 6, 8])


In [19]:
# Using linspace
print("Using linspace ->",torch.linspace(0,10,10))

Using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])


In [23]:
# Using eye(Identity Metrix)
print("Using full -> ",torch.eye(5))

Using full ->  tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])


In [21]:
# Using full
print("Using full -> ",torch.full((3,3),5))

Using full ->  tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


#Finding out Tensor Shape.

In [24]:
x = torch.tensor([[1,2,3],[2,3,4]])
x

tensor([[1, 2, 3],
        [2, 3, 4]])

In [25]:
x.shape

torch.Size([2, 3])

In [26]:
# For creating similar shape Tensor(Values are different but same shape).
torch.empty_like(x)

tensor([[    132405288218000,            46902304,                   0],
        [                  0,                   0, 7310593858020254331]])

In [27]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [28]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [33]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

#Tensor Data Type.

In [29]:
x.dtype

torch.int64

In [30]:
torch.tensor([1.0,2.0,3.3],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [31]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [32]:
# Using to() function for specifying the dtype.
x.to(torch.float32)

tensor([[1., 2., 3.],
        [2., 3., 4.]])